### ISSUE TITLE
Enhancing the CSS.

### ISSUE THREAD

**Issue by Shristhi0331** [Shristhi0331/Nykaa#1]
Making the UI/UX better and more presentable.

**Comment by anandtharad** [comment]
@Shristhi0331 What kind of UI do you want? can you show some ideas for the ui

**Comment by charvibhargava** [comment]
I am a web developer developing websites since last 1 year. I am pretty good at the UI and all stuffs. Please assign this to me. I can try and add some animations and make it more beautiful and more presentable.

**Comment by Shristhi0331** [comment]
Sorry it was already assigned to someone .if there is any other issue then
I would assign it to you.

**Comment by Kumar-Harshit223** [comment]
Assign me this issue.
