### ISSUE TITLE
Adding a customer bill form

### ISSUE THREAD

**Issue by Swastik200** [Shristhi0331/Nykaa#6]
Creating a bill with details which will lead u to vote of thanks screen

**Comment by Swastik200** [comment]
Any updates plz

**Comment by Shristhi0331** [comment]
ok you are assigned fot this.

**Comment by Shristhi0331** [comment]
Yes you are assigned for this.

**Comment by Swastik200** [comment]
It's done plz check and confirm

**Comment by Shristhi0331** [comment]
It's fine but I think you should do some changes in its css .
It is not looking alike to nykaa's css

**Comment by Swastik200** [comment]
Ok, I'll check it out.

**Comment by Swastik200** [comment]
Plz check and confirm

**Comment by Swastik200** [comment]
Plz check and confirm

**Comment by Swastik200** [comment]
Plz check and confirm
